import './globals.css'
import { Inter } from 'next/font/google'

import Navbar from '../components/navbar/Navbar';
import Footer from '../components/footer/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'trello clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      
      <body className={`${inter.className} `}>
        <nav>
          <Navbar />
        </nav>
        {children}
        <footer className='w-full h-full py-[40px] bg-blue-950'>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
