

import './globals.css'
import { Inter } from 'next/font/google'
import { useState } from 'react';


import Navbar from '../components/navbar/Navbar';
import Footer from '../components/footer/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'trello clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [active, setActive] = useState("");

  return (
    <html lang="en">
      
      <body className={`${inter.className} ${active && "overflow-hidden"}`}>
        <nav>
          <Navbar active={active} setActive={setActive} />
        </nav>
        {children}
        <footer className='w-full h-full py-10 bg-blue-950'>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
